version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.16
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.3
    - 6.2.7
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
